### ISSUE TITLE
Making a Polygon with `std::64::INFINITY` loops forever

### ISSUE THREAD

**Issue by wucke13** [myelin-ai/geometry#36]
I have a usecase where I want to checke whether a 2D point is inside of an envelope, and said envelope extends to infinity in one direction. I would like to use this library find out whether points fall in this envelope. Is it possible to make this possible?

Currently it seems to just block the code, which is definitely not right. It should either fail or not accept INFINITY in the first place.

An interesting problem here is: What to do if we have an angled line to infinity?

```rust
 PolygonBuilder::default()
            .vertex(1.0, 1.0) // easy
            .vertex(1.0, 2.0) // easy
            .vertex(std::f64::INFINITY., 2.0) // still easy, as the y parameter is the same as in the vertex before
            .vertex(2200.0, 1.0) // tricky, what is the derivation of a slope which goes +1 in y and +infinity in x?
            .build().expect("infailabile");
```

I only need this to work for the simple cases, where infinity goes in one dimension, and the value in the other dimension is the same as the last vertex without infinity. However, the possibility of tricky input must be addressed in some way.

**Comment by jeremystucki** [comment]
I think this use case is not in the scope of the library. We should add a check against this though.

**Comment by tautropfli** [comment]
The fix which explicitly disallows infinity is now live on [crates.io](https://crates.io/crates/myelin-geometry) as part of the [2.4.2](https://github.com/myelin-ai/geometry/releases/tag/2.4.2) release.
